apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: sanidhyamalhotra/todolist:latest  # ← Docker Hub image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  selector:
    app: todolist
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer  # Makes the app accessible externally	